export const ADD_INGREDIENTS= 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS= 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS= "SET_INGREDIENTS";
export const ERROR_FETCHING_INGREDIENTS= "ERROR_FETCHING_INGREDIENTS";

export const PURCHASE_START="PURCHASE_START"
export const PURCHASE_SUCCESS="PURCHASE_SUCCESS";
export const PURCHASE_FAILED="PURCHASE_FAILED";

export const SET_ORDERS= "SET_ORDERS"
export const ERROR_FETCHING_ORDERS= "ERROR_FETCHING_ORDERS"

export const AUTH_START="AUTH_START"
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAILED="AUTH_FAILED";
export const AUTH_LOGOUT="AUTH_LOGOUT";
export const AUTH_CHECK_SESSION = "AUTH_CHECK_SESSION"